/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import controller.ProjectController;
import java.sql.Date;
import java.util.List;
import java.util.Scanner;
import model.Project;

public class Main {
     public static void main(String[] args) {

         Scanner sc = new Scanner(System.in);
     ProjectController projectController = new ProjectController();
        
        Project project = new Project();
        
        //project.setId(1);
        //project.setNome("Projeto Teste 4");
        //project.setDescricao("Teste de projetos 4 ");
        //project.setData_criacao(new Date(01/01/2023));
        //project.setData_att(new Date(28/04/2023));        
        //projectController.save(project);
    
        List<Project> projects = projectController.getAll();
        System.out.println("A quantidade de projetos é:" + projects.size());
        //System.out.println("Nome: " + projects.getClass().getName());
        /*
        int i = 0;
        
        System.out.println("Digite o projeto a ser excluido");
        i = sc.nextInt();
        
        projectController.removeById(i);
        */
        
        
        
        
    }
}

